[package]
name = "os"
version = "0.1.0"
authors = ["Marek Rogalski <mafikpl@gmail.com>"]

[dependencies]
hyper = "*"
websocket = "*"
serde_json = "1.0"
serde = "*"
euclid = "*"
rusttype = "*"
ref_eq = "*"
libc = "*"